In [2]:
import re
target_str = "My roll number is 25"
res = re.findall(r"\d", target_str)
#extract matching value
print(res)
print(type(res))

['2', '5']
<class 'list'>


In [8]:
import re
stri = "From: stephen.a.smith@espn.com, drake@hotmail.com, frenchMontana@gmail.com"
stri = stri.rstrip()
print(re.findall("From: .+@", stri))


['From: stephen.a.smith@espn.com, drake@hotmail.com, frenchMontana@']


In [9]:
stri = 'From: stephen.a.smith@espn.com, drake@hotmail.com, frenchMontana@gmail.com'
#stri = stri.strip()

print(re.findall(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b',stri))

['stephen.a.smith@espn.com', 'drake@hotmail.com', 'frenchMontana@gmail.com']


ELINK 341.3: REGEX VIDEO
pt 1

In [10]:
#using re.serach() like startswith()


hand = open('mbox-short.txt')
for line in hand:
    line = line.rstrip()
    if line.startswith('From:'):
        print(line)

#regex version:
import re
hand = open('mbox-short.txt')
for line in hand:
    line = line.rstrip()
    if re.search('^From:', line):
        print(line)

FileNotFoundError: [Errno 2] No such file or directory: 'mbox-short.txt'

In [ ]:
#wild-card characters

    #the . character matches any character
    #if you add the * character, the character is "any number of times"


#fine-tuning your match
    #depending on how clean your data is, and the purpose of your application, you may want to narrow your match down a bit

In [13]:
#matching and extracting data

#re.search returns a true/false depending on whether string matches the regular expression
#re.findall() if we actually want the matching strings to be extracted

import re
x = "My 2 favorite numbers are 19 and 42"
y = re.findall('[0-9]+', x)   #[0-9]+ means 1 or more digits
print(y)

['2', '19', '42']


In [15]:
#warning: greedy match

#the repeat characters (* and +) push outward in both directions (greedy) to match the largest possible string

import re
x = "From: using the : character"
y = re.findall('F.+:', x)
print(y)


['From: using the :']


In [16]:
#non-greedy matching

#not all regular expression repeat codes are greedy!
#if you add a ? character, the + and * chill out a bit

import re
x = "From: using the : character"
y = re.findall('^F.+?:', x)
print(y)

['From:']


In [18]:
#fine-tuning string extraction

#you can refine the match for re.findall() and separately determine which portion of the match is to be extracted by using parentheses

x = "From stephen.marquard@uct.ac.za Sat Jan 5 09:14:16 2008"
y = re.findall('\S+@\S+', x)
print(y)

['stephen.marquard@uct.ac.za']


In [19]:
data = "From stephen.marquard@uct.ac.za Sat Jan 5 09:14:16 2008"
atpos = data.find('@')
print(atpos)

sppos = data.find(' ', atpos)
print(sppos)

host = data[atpos+1: sppos]
print(host)

21
31
uct.ac.za


In [22]:
#double split pattern

#sometimes we split a line one way, and then grab one ofthe pieces of the line and split that piece again

line = "From stephen.marquard@uct.ac.za Sat Jan 5 09:14:16 2008"

words = line.split()
email = words[1]
pieces = email.split('@')
print(pieces[1])


#regex version
import re
lin = "From stephen.marquard@uct.ac.za Sat Jan 5 09:14:16 2008"
y = re.findall('@([^ ]*)', lin)
print(y)

#even cooler regex version
import re
lin = "From stephen.marquard@uct.ac.za Sat Jan 5 09:14:16 2008"
y = re.findall('^From .*@([^ ]*)', lin)
print(y)

uct.ac.za
['uct.ac.za']
['uct.ac.za']


In [24]:
#spam confidence

import re
hand = open('mbox-short.txt')
numlist = list()
for line in hand:
    line = line.rstrip()
    stuff = re.findall('^X-DSPAM-Confidence: ([0-9.]+)', line)
    if len(stuff) != 1: continue
    num = float(stuff[0])
    numlist.append(num)
print('Maximum:', max(numlist))

FileNotFoundError: [Errno 2] No such file or directory: 'mbox-short.txt'

In [25]:
#escape character

import re
x = 'We just received $10.00 for cookies.'
y = re.findall('\$[0-9]+', x)
print(y)

['$10']


NUMPY VIDEO NOTES

https://www.youtube.com/watch?v=xECXZ3tyONo&t=602s&pp=ygUKbnVtcHkgaW4gNQ%3D%3D

In [35]:
import numpy as np

a = np.zeros(3)

type(a) #output: import numpy as np
type(a[0])  #output: numpy.float64

#a #output: array([0., 0., 0.])
print(a) #output: [0. 0. 0.]

#this is an effective way to make an empty array of 0s as a placeholder(?)


[0. 0. 0.]


In [36]:
z = np.zeros(10)

In [54]:
z.shape #output: (10,)

?z.shape 
#prints a doc string of info about it

Type:        tuple
String form: (5,)
Length:      1
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [38]:
z.shape = (10, 1)
z 

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [39]:
z = np.ones(10)
z #output: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
z = np.empty(3)
z #output: array([ 9.06028671e-312,  9.06040514e-312, -0.00000000e+000])

array([ 9.06028671e-312,  9.06040514e-312, -0.00000000e+000])

In [50]:
z = np.linspace(2, 10, 5) #from 2 to 10, with 5 elements. useful for plots/graphs
#also, different from range() in that it's inclusive of 10, and 5 means 5 elements rather than steps of 5

z #output: z = np.array([10, 20]) #output: array([10, 20])

array([ 2.,  4.,  6.,  8., 10.])

In [44]:
z = np.array([10, 20]) #output: array([10, 20])
z

array([10, 20])

In [49]:
a_list = [1,2,3,4,5,6,7]
z = np.array(a_list) #output: array([1, 2, 3, 4, 5, 6, 7])
z

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
type(z) #output: type(z)

numpy.ndarray

In [57]:
#np can do a lot of randomization 

np.random.seed(0)
z1 = np.random.randint(10, size=6)
z1

array([5, 0, 3, 3, 7, 9])

In [58]:
z1[0] #first element of array

5

In [59]:
z1[0:2]

array([5, 0])

In [60]:
z1[-1]

9

In [ ]:
from skimage import 

In [64]:
import matplotlib.pyplot as plt
#plt.imshow(photo::-1)

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
plt.imshow(photo[50:150, 150:280])

In [ ]:
plt.imshow(photo[:, ::-1])

In [ ]:
plt.imshow(photo[::2, ::2])

In [ ]:
photo
photo_sin = np.sin(photo)
photo_sin
#run the values of the pixels, etc

In [65]:
print(np.sum(photo))
print(np.prod(photo))
print(np.mean(photo))
print(np.std(photo))
print(np.var(photo))
print(np.min(photo))
print(np.max(photo))
print(np.argmin(photo))
print(np.argmax(photo))

NameError: name 'photo' is not defined

In [68]:
z = np.array([1,2,3,4,5])

In [69]:
z < 3

array([ True,  True, False, False, False])

In [70]:
z > 3

array([False, False, False,  True,  True])

In [71]:
z[z > 3]

array([4, 5])

In [72]:
photo.masked = np.where(photo > 100, 255, 0)

NameError: name 'photo' is not defined

In [ ]:
plt.imshow(photo_masked)

In [73]:
a_array = np.array([1,2,3,4,5])
b_array = np.array([6,7,8,9,10])

In [74]:
a_array + b_array

array([ 7,  9, 11, 13, 15])

In [75]:
a_array + 30

array([31, 32, 33, 34, 35])

In [76]:
a_array * b_array

array([ 6, 14, 24, 36, 50])

In [77]:
a_array * 10

array([10, 20, 30, 40, 50])

In [78]:
a_array @ b_array #dot product of the two arrays

130

In [ ]:
plt.imshow(photo[:,:,0].T)

In [80]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [ ]:
#pip install numpy
            